version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"   # Web UI
      - "222:22"      # SSH for Git
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.easyfluff.com`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  drone-server:
    image: drone/drone:2
    container_name: drone-server
    restart: always
    volumes:
      - ./drone-data:/data
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_RPC_SECRET=${POSTGRES_PASSWORD}
      - DRONE_SERVER_HOST=easyfluff.com
      - DRONE_SERVER_PROTO=http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`easyfluff.com`)"
      - "traefik.http.routers.drone.entrypoints=web"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
    networks:
      - traefik-public

  drone-runner:
    image: drone/drone-runner-docker:latest
    container_name: drone-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server:80
      - DRONE_RPC_SECRET=${POSTGRES_PASSWORD}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
