version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://grafana.halfagiraf.com
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.grafana-router.rule=Host(`grafana.halfagiraf.com`)"
      - "traefik.http.routers.grafana-router.entrypoints=websecure"
      - "traefik.http.routers.grafana-router.tls=true"
      - "traefik.http.routers.grafana-router.priority=100"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - traefik-public
      - monitoring-network

  loki:
    image: grafana/loki:2.7.1
    container_name: loki
    # Remove "user: '0'" so that Loki runs as the default non-root user.
    command:
      [
        "sh",
        "-c",
        "mkdir -p /loki/index/uploader /loki/cache /loki/chunks /loki/wal && chown -R 10001:10001 /loki && exec loki --config.file=/etc/loki/local-config.yaml",
      ]
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_chunks:/loki/chunks
      - loki_index:/loki/index
      - loki_wal:/loki/wal
      - loki_cache:/loki/cache
    ports:
      - "3100:3100"
    networks:
      - monitoring-network

  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/promtail-config.yaml:/etc/promtail/promtail.yaml:ro
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - monitoring-network

volumes:
  grafana_data:
  loki_chunks:
  loki_index:
  loki_wal:
  loki_cache:

networks:
  traefik-public:
    external: true
  monitoring-network:
    driver: bridge
