version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - db-network
  harvest:
    build:
      context: ./site1/harvest
      dockerfile: Dockerfile.harvest
    container_name: harvest_app
    restart: always
    depends_on:
      - postgres # ensures Postgres is up
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${HARVEST_POSTGRES_DB}
      API_KEY_1: ${API_KEY_1}
      API_KEY_2: ${API_KEY_2}
      API_KEY_3: ${API_KEY_3}
    networks:
      - db-network # <-- add this
  pgadmin:
    image: dpage/pgadmin4:6.21
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  db-network:
    external: true
