version: "3"

services:
  site3:
    build: .
    labels:
      - "traefik.docker.network=traefik-public" # Explicit network for Traefik
      - "traefik.enable=true"
      # Primary (canonical) router for the domain
      - "traefik.http.routers.site3-router.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.site3-router.entrypoints=web"
      - "traefik.http.routers.site3-router.tls=true"
      - "traefik.http.services.site3.loadbalancer.server.port=3000"

      # Additional router for domain that applies a 301 redirect for www
      - "traefik.http.routers.site3-www.rule=Host(`www.${SITE_DOMAIN}`)"
      - "traefik.http.routers.site3-www.entrypoints=web"
      - "traefik.http.routers.site3-www.middlewares=redirect-to-nonwww-site3"

      # Define the redirect middleware with unique naming for site3
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.regex=^https?://www\\.${SITE_DOMAIN}(.*)"
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.replacement=https://${SITE_DOMAIN}$1"
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.permanent=true"

    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - traefik-public
      - db-network
networks:
  traefik-public:
    external: true
  db-network:
    external: true
