version: "3"

services:
  site3:
    build: .
    labels:
      - "traefik.docker.network=traefik-public" # Ensure proper network
      - "traefik.enable=true"

      # Primary router for halfagiraf.com (HTTPS)
      - "traefik.http.routers.site3-router.rule=Host(`halfagiraf.com`)"
      - "traefik.http.routers.site3-router.entrypoints=websecure"
      - "traefik.http.routers.site3-router.tls=true"
      - "traefik.http.services.site3.loadbalancer.server.port=3000"

      # Router for www.halfagiraf.com that redirects (HTTP)
      - "traefik.http.routers.site3-www.rule=Host(`www.halfagiraf.com`)"
      - "traefik.http.routers.site3-www.entrypoints=web"
      - "traefik.http.routers.site3-www.middlewares=redirect-to-nonwww-site3"

      # Unique redirect middleware for site3
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.regex=^https?://www\\.halfagiraf\\.com(.*)"
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.replacement=https://halfagiraf.com$1"
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.permanent=true"

    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - traefik-public
      - db-network
networks:
  traefik-public:
    external: true
  db-network:
    external: true
