version: "3"

services:
  site3:
    build: .
    labels:
      - "traefik.docker.network=traefik-public" # Explicit network for Traefik
      - "traefik.enable=true"

      # Primary (canonical) router for the domain using SITE_DOMAIN
      - "traefik.http.routers.site3.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.site3.entrypoints=web"
      - "traefik.http.routers.web-secure.tls=true" # Global TLS flag (as in your working config)
      - "traefik.http.services.site3.loadbalancer.server.port=3000"

      # Additional router for the www redirect with a unique middleware name
      - "traefik.http.routers.site3-www.rule=Host(`www.${SITE_DOMAIN}`)"
      - "traefik.http.routers.site3-www.entrypoints=web"
      - "traefik.http.routers.site3-www.middlewares=redirect-to-nonwww-site3"

      # Unique redirect middleware for site3
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.regex=^https?://www\\.${SITE_DOMAIN}(.*)"
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.replacement=https://${SITE_DOMAIN}$1"
      - "traefik.http.middlewares.redirect-to-nonwww-site3.redirectregex.permanent=true"

    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - traefik-public
      - db-network
networks:
  traefik-public:
    external: true
  db-network:
    external: true
  monitoring-network:
    external: false   # or specify driver if needed
