global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # New job for site1
  - job_name: "site1"
    static_configs:
      - targets: ["site1:3000"]
  # You can add additional scrape jobs for your services here
  # For example, if you have a node_exporter running on a container:
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
