version: "3"

services:
  site2:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site2.rule=Host(`site2.localhost`)"
      - "traefik.http.routers.site2.entrypoints=web"
      - "traefik.http.services.site2.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-public" # Explicit network for Traefik
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - traefik-public
      - db-network

networks:
  traefik-public:
    external: true
  db-network:
    external: true
